const fs = require('fs')
const path = require('path')

const { faker } = require('@faker-js/faker')

const brands = [
  'Peloton',
  'Netflix',
  'Costco',
  'Chick-fil-A',
  'Amazon',
  'Apple',
  'Nike',
  'Target',
  'Google',
  'Spotify',
  "Trader Joe's",
  'Zoom Video Communications',
  'The Walt Disney Company',
  'ROBLOX',
  'In-N-Out Burger',
  'Vans',
  'Nintendo',
  'Headspace Health',
  'REI',
  'Lego Group',
  'Delta Air Lines',
  'Microsoft',
  'Instagram',
  'Southwest Airlines',
  'American Eagle Outfitters',
  'Glossier',
  'Rockstar Games',
  'CHANEL',
  'LinkedIn',
  'Uniqlo',
  'PlayStation',
  'Tesla',
  'Starbucks',
  'NVIDIA',
  'Salesforce / Slack',
  'Honda',
  'Audi',
  'Red Bull',
  'Colgate Palmolive',
  'Bath &amp; Body Works',
  'Mercedes-Benz USA',
  'Hershey Company',
  "Dunkin'",
  'Porsche',
  'Chipotle',
  'BMW Group',
  'Pinterest',
  'Logitech',
  'Ritz-Carlton',
  'Shopify',
  'Crocs',
  'Gucci',
  'AMD',
  'Tiffany &amp; Co',
  'The Coca-Cola Company',
  'Rooster Teeth',
  'National Geographic',
  'adidas',
  'SEPHORA',
  'HBO',
  'Mars',
  'American Express',
  'PUMA',
  'Versace',
  'Visa',
  'Adobe',
  'Square',
  'Whole Foods Market',
  'Unilever',
  'USAA',
  'Cisco',
  'JPMorgan Chase &amp; Co',
  'Bungie',
  'MAC Cosmetics',
  'YouTube',
  'LVMH',
  'Riot Games',
  'Airbnb',
  'Marriott',
  'Ubisoft',
  'ZoomInfo',
  'Toyota',
  'Tommy Hilfiger',
  'Hilton',
  "McDonald's",
  'The Home Depot',
  'Baskin Robbins',
  'Mastercard',
  'Johnson &amp; Johnson',
  'Uber',
  'Twitter',
  'Procter &amp; Gamble',
  '7-Eleven',
  'Coinbase',
  'FedEx',
  '3M',
  'Nordstrom',
  'Philips',
  'Bose',
  'Foot Locker',
]

const random1000Products = Array.from({ length: 1000 }, createRandomProduct)

function createRandomProduct() {
  return {
    id: faker.datatype.uuid(),
    artNumber: parseInt(faker.random.numeric(12)),
    name: faker.commerce.productName(),
    brand: faker.helpers.arrayElement(brands),
    weight: parseInt(faker.random.numeric(4)),
    quantity: parseInt(faker.random.numeric(4)),
    price: faker.commerce.price(),
    stock: parseInt(faker.random.numeric(4)),
  }
}

fs.writeFileSync(
  path.join(__dirname, 'data.json'),
  JSON.stringify(random1000Products)
)
